apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliff-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cliff-ai
  template:
    metadata:
      labels:
        app: cliff-ai
    spec:
      containers:
        - name: cliff-ai
          image: soumikdey/cliff-ai-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cliff-ai
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cliff-ai
